version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: file_vault_backend
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,localhost:8000,backend:8000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: file_vault_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    restart: always

volumes:
  media_data:

networks:
  default:
    driver: bridge