# Generated by Django 4.2.2 on 2025-04-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data', models.BinaryField()),
                ('size', models.PositiveIntegerField()),
                ('reference_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('content_type', models.CharField(db_index=True, max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.filecontent')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
